#%RAML 1.0
---

title: Organisations Matching
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Data availability
   content: !include docs/data-availability.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/organisations/matching:
  /corporation-tax:
      post:
        displayName: "Match Corporation Tax details for an organisation "
        description: !include docs/post-corporation-tax-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned" ] } ]
        (annotations.sandboxData): !include sandbox/corporation-tax-organisations-matching-request.md
        headers:
          CorrelationId:
            description: !include ./includes/correlationId.md
            type: string
            required: true
            example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
          Content-Type:
            description: Specifies the format of the request body. This must be JSON.
            type: string
            required: true
            example: "application/json"
        body:
          application/json:
            type: !include schemas/corporation-tax-matching-request.json
            example: !include examples/corporation-tax-matching-request-example.json
        responses:
          200:
            description: "Returns a matchId which can be used to make calls to details endpoints"
            body:
              application/json:
                type: !include schemas/corporation-tax-matching-response.json
                example: !include examples/corporation-tax-matching-response-example.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: "The request body does not conform to the schema"
                    value:
                      code: BAD_REQUEST
          403:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  Forbidden:
                    description: "The organisation's details provided did not match with HMRC's records"
                    value:
                      code: MATCHING_FAILED
  /self-assessment:
      post:
        displayName: Match Self Assessment details for an organisation
        description: !include docs/post-self-assessment-tax-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned" ] } ]
        (annotations.sandboxData): !include sandbox/self-assessment-matching-request.md
        headers:
          CorrelationId:
            description: !include ./includes/correlationId.md
            type: string
            required: true
            example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
          Content-Type:
            description: Specifies the format of the request body. This must be JSON.
            type: string
            required: true
            example: "application/json"
        body:
          application/json:
            type: !include schemas/sautr-matching-request.json
            example: !include examples/sautr-matching-request-example.json
        responses:
          200:
            description: "Returns a matchId which can be used to make calls to details endpoints"
            body:
              application/json:
                type: !include schemas/sautr-matching-response.json
                example: !include examples/sautr-matching-response-example.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: "The request body does not conform to the schema"
                    value:
                      code: BAD_REQUEST
          403:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  Forbidden:
                    description: "The organisation's details provided did not match with HMRC's records"
                    value:
                      code: MATCHING_FAILED
  /corporation-tax/{matchId}:
      uriParameters:
        matchId:
          description: "A short-lived universally unique identifier (UUID), typically valid for 5 hours. Generated through the Organisations Matching API."
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      get:
        displayName: "Get links to Corporation Tax and number of employee details for a matched organisation"
        description: !include docs/get-corporation-tax-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned" ] } ]
        (annotations.sandboxData): !include sandbox/corporation-tax-matched-details-response.md
        headers:
          CorrelationId:
            description: !include ./includes/correlationId.md
            type: string
            required: true
            example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
        responses:
          200:
            description: "The company's Corporation Tax details"
            body:
              application/json:
                type: !include schemas/corporation-tax-details-response.json
                example: !include examples/corporation-tax-details-response-example.json
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: "Not Found"
                    value:
                      code: NOT_FOUND
  /self-assessment/{matchId}:
      uriParameters:
        matchId:
          description: "A short-lived universally unique identifier (UUID), typically valid for 5 hours. Generated through the Organisations Matching API."
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      get:
        displayName: "Get links to Self Assessment and number of employees details for a matched organisation"
        description: !include docs/get-self-assessment-tax-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned" ] } ]
        (annotations.sandboxData): !include sandbox/self-assessment-matched-details-response.md
        headers:
          CorrelationId:
            description: !include ./includes/correlationId.md
            type: string
            required: true
            example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
        responses:
          200:
            description: "The Organisation's Self Assessment details"
            body:
              application/json:
                type: !include schemas/sautr-details-response.json
                example: !include examples/sautr-details-response-example.json
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: "Not Found"
                    value:
                      code: NOT_FOUND