#%RAML 1.0
---

title: Organisations Matching
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/organisations:
  /matching/paye:
      post:
        displayName: "PAYE Matching Request"
        description: "Matches posted information with known facts and generates the matchID"
        is: [headers.acceptHeader, headers.contentHeader]
        (annotations.scope): "read:organisations-matching"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:organisations-matching" ] } ]
        (annotations.sandboxData): !include sandbox/paye-sandbox-data.md
        headers:
          CorrelationId:
            description: !include ./includes/correlationId.md
            type: string
            required: true
            example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
        queryParameters:
          matchId:
            description: "A short-lived universally unique identifier (UUID), typically valid for several hours. Generated through the Organisations Matching API."
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        body:
          application/json:
            type: !include schemas/paye-matching-request.json
            example: !include examples/paye-matching-request-example.json
        responses:
          200:
            description: "Returns a matchId which can be used to make calls to details endpoints"
            body:
              application/json:
                type: !include schemas/paye-matching-response.json
                example: !include examples/paye-matching-response-example.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: "The request body does not conform to the schema"
                    value:
                      code: BAD_REQUEST
          403:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  Forbidden:
                    description: "The organisation's details provided did not match with HMRC's records"
                    value:
                      code: MATCHING_FAILED

  /matching/self-assessment:
      post:
        displayName: Self Assessment Matching Request
        description: "This endpoint takes a JSON body that contains a UTR, Organisation Type and Known Facts in order to match against HMRC's records. Upon a successful match, a matchId is returned which can be used in subsequent calls."
        is: [headers.acceptHeader, headers.contentHeader]
        (annotations.scope): "read:organisations-matching"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:organisations-matching" ] } ]
        (annotations.sandboxData): !include sandbox/sa-sandbox-data.md
        headers:
          Content-Type:
            description: "Specifies the content-type of the body."
            type: string
            required: true
            example: application/json
          CorrelationId:
            description: !include ./includes/correlationId.md
            type: string
            required: true
            example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
        body:
          application/json:
            type: !include schemas/sautr-matching-request.json
            example: !include examples/sautr-matching-request-example.json
        responses:
          200:
            description: "Returns a matchId which can be used to make calls to details endpoints"
            body:
              application/json:
                type: !include schemas/sautr-matching-response.json
                example: !include examples/sautr-matching-response-example.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: "The request body does not conform to the schema"
                    value:
                      code: BAD_REQUEST
          403:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  Forbidden:
                    description: "The organisation's details provided did not match with HMRC's records"
                    value:
                      code: MATCHING_FAILED
  /matching/paye/{matchId}:
      uriParameters:
        matchId:
          description: "A short-lived UUID, typically valid for 5 hours"
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      get:
        displayName: "Get matched organisation's PAYE details"
        description: "This endpoint takes a matchId and returns corporation tax information for the company"
        is: [headers.acceptHeader, headers.contentHeader]
        (annotations.scope): "read:organisations-matching"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:organisations-matching" ] } ]
        (annotations.sandboxData): !include sandbox/paye-sandbox-data.md
        headers:
          CorrelationId:
            description: !include ./includes/correlationId.md
            type: string
            required: true
            example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
        responses:
          200:
            description: "The company's Corporation Tax details"
            body:
              application/json:
                type: !include schemas/paye-details-response.json
                example: !include examples/paye-details-response-example.json
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: "Not Found"
                    value:
                      code: NOT_FOUND
  /matching/self-assessment/{matchId}:
      uriParameters:
        matchId:
          description: "A short-lived UUID, typically valid for several hours"
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      get:
        displayName: "Get matched organisation's self-assessment details"
        description: "This endpoint takes a matchId and returns self assessment information for the organisation"
        is: [headers.acceptHeader, headers.contentHeader]
        (annotations.scope): "read:organisations-matching"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:organisations-matching" ] } ]
        (annotations.sandboxData): !include sandbox/sa-sandbox-data.md
        headers:
          CorrelationId:
            description: !include ./includes/correlationId.md
            type: string
            required: true
            example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
        responses:
          200:
            description: "The Organisation's Self Assessment details"
            body:
              application/json:
                type: !include schemas/sautr-details-response.json
                example: !include examples/sautr-details-response-example.json
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: "Not Found"
                    value:
                      code: NOT_FOUND